version: '3'
services:
  springboot-app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: springboot-app-container
    depends_on:
      - mysql-db
      - redis
      - mongo
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/alttab_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/alttab_db
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      
  executor-app:
    build:
      context: ./executor
    ports:
      - "8081:8081"
    container_name: executor-app-container
    depends_on:
      - mysql-db
      - redis
      - mongo
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/alttab_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/alttab_db
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  react-app:
    build:
      context: ./frontend
    container_name: react-app-container
    ports:
      - "3000:3000"

  mysql-db:
    image: mysql:latest
    container_name: mysql-db-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: alttab_db
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management UI

volumes:
  mysql-data:
    external: true









 
